# Generated by Django 3.0.5 on 2020-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gcam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('config', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
